[ITA-214] Check logs for correct XGBoost backend

diff --git a/scripts/jenkins/Makefile.jenkins b/scripts/jenkins/Makefile.jenkins
--- a/scripts/jenkins/Makefile.jenkins
+++ b/scripts/jenkins/Makefile.jenkins
@@ -229,15 +229,29 @@ test-xgb-smoke-omp-jenkins:
 	find . -name 'test*Node.sh' -type f -exec sed -i 's/cat $$OUTDIR\/out*/echo "###### Printing last 400 lines of logs. Check artifacts for more. ######"; tail -n 400 $$OUTDIR\/out*/g' {} +
 	@$(MAKE) -f $(THIS_FILE) test-xgb-smoke-omp
 
-test-xgb-smoke-minimal test-xgb-smoke-omp:
-	./gradlew h2o-ext-xgboost:test
-
 test-xgb-smoke-gpu-jenkins:
 	find . -name 'test*Node.sh' -type f -exec sed -i 's/cat $$OUTDIR\/out*/echo "###### Printing last 400 lines of logs. Check artifacts for more. ######"; tail -n 400 $$OUTDIR\/out*/g' {} +
 	@$(MAKE) -f $(THIS_FILE) test-xgb-smoke-gpu
 
+test-xgb-smoke-minimal:
+	./gradlew h2o-ext-xgboost:test
+	$(call check_xgb_backend,'xgboost4j_minimal')
+
+test-xgb-smoke-omp:
+	./gradlew h2o-ext-xgboost:test
+	$(call check_xgb_backend,'xgboost4j_\(omp\|gpu\)')
+
 test-xgb-smoke-gpu:
 	scripts/test-xgb-gpu-smoke.sh
+	$(call check_xgb_backend,'xgboost4j_gpu')
+
+define check_xgb_backend
+	@if [ ! "$$(egrep 'Found XGBoost backend with library: $(1)' h2o-extensions/xgboost/sandbox/single/*)" ]; then \
+		echo "Cannot find XGBoost backend $(1) in the logs."; \
+		echo "Please check logs in h2o-extensions/xgboost/sandbox/single"; \
+		exit 1; \
+	fi
+endef
 
 benchmark:
 	Rscript ml-benchmark/h2oR/benchmark.R -d $$DATASETS_PATH -t $$TEST_CASES_PATH -o $$OUTPUT_PREFIX --git-sha $$GIT_SHA --git-date "$$GIT_DATE" --model $$BENCHMARK_MODEL --build-id $$BUILD_ID
