Fix: JSON Injection Vulnerability in Slack Alerts (#16514)
* fix: Add validation for issue title and URL in Slack alerts workflow

* fix: Modify issue title and URL to use env variables

diff --git a/.github/workflows/slack-alerts.yml b/.github/workflows/slack-alerts.yml
--- a/.github/workflows/slack-alerts.yml
+++ b/.github/workflows/slack-alerts.yml
@@ -8,6 +8,24 @@ jobs:
   send-slack-alert:
     runs-on: ubuntu-latest
     steps:
+
+    - name: Check issue title and URL
+      id: check
+      env:
+        ISSUE_TITLE: ${{ github.event.issue.title }}
+        ISSUE_URL: ${{ github.event.issue.html_url }}
+      run: |
+        if [[ ! "$ISSUE_TITLE" =~ ^[a-zA-Z0-9\ \-\_]+$ ]]; then
+          echo "Invalid characters in issue title"
+          exit 1
+        fi
+        if [[ ! "$ISSUE_URL" =~ ^https:\/\/[a-zA-Z0-9\.\-\/\_\?\=\&]+$ ]]; then
+          echo "Invalid characters in issue URL"
+          exit 1
+        fi
+        echo "TITLE=$ISSUE_TITLE" >> $GITHUB_ENV
+        echo "URL=$ISSUE_URL" >> $GITHUB_ENV
+
     - name: Post to a Slack channel
       id: slack
       uses: slackapi/slack-github-action@v1.23.0
@@ -18,7 +36,7 @@ jobs:
             "text": ":github: *H2O-3 GitHub Issue Opened*",
             "attachments": [
               {
-                "text": "*Title:* ${{ github.event.issue.title }}\n*Link:* ${{ github.event.issue.html_url }}",
+                "text": "*Title:* ${{ env.TITLE }}\n*Link:* ${{ env.URL }}",
                 "color": "good",
                 "fallback": "Build Alert"
               }
